<h1>Numpy Array</h1>

Numpy Array

In [2]:
import numpy as np
np_arr = np.arange(100000)

In [4]:
nu_list = []
for i in range(100000):
    nu_list.append(i)

In [5]:
nu_list = [i for i in range(100000)]

In [9]:
%%time
for i in range(100):
    sum(nu_list)

Wall time: 178 ms


In [15]:
%%time
for i in range(100):
    np.sum(np_arr)

Wall time: 8 ms


1차원 배열(array) 만들기

In [20]:
vector = np.array([1, 4, 7, 10], float)
vector

array([ 1.,  4.,  7., 10.])

In [21]:
type(vector)

numpy.ndarray

In [22]:
vector.shape

(4,)

In [23]:
matrix = np.array([[1,2,5,8], [2,3,4,9], [4,5,6,7]])
matrix

array([[1, 2, 5, 8],
       [2, 3, 4, 9],
       [4, 5, 6, 7]])

In [24]:
matrix.shape

(3, 4)

3차원 배열 만들기

In [25]:
t_list = [[[1,2,5,8], [2,3,4,9], [4,5,6,7]], [[1,2,5,8], [2,3,4,9], [4,5,6,7]], [[1,2,5,8], [2,3,4,9], [4,5,6,7]], [[1,2,5,8], [2,3,4,9], [4,5,6,7]]]
tensor = np.array(t_list)
tensor

array([[[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]]])

In [26]:
tensor.shape

(4, 3, 4)

<h3>Array Shape</h3>

ndim & size

In [28]:
vector.ndim, matrix.ndim, tensor.ndim

(1, 2, 3)

In [29]:
vector.size, matrix.size, tensor.size

(4, 12, 48)

### dtype

In [31]:
a = np.array([[1, 2, 3], [4.5, '5', '6']], dtype=np.float32)
a

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [32]:
a.nbytes

24

In [33]:
vector.nbytes

32

Reshape

In [37]:
test_matrix = np.array([[1,2,3,4], [5,6,7,8]])
test_matrix.shape

(2, 4)

In [38]:
test_matrix.reshape(8,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
test_matrix.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
test_matrix.reshape(-1,2)       ## test_matrix.reshape(4,2)와 동일

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [41]:
test_matrix.reshape(2,-1,2)      ## test_matrix.reshape(2,2,2)와 동일

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#### flatten

In [43]:
test_matrix.flatten()       ## 속성이 아니라, 동작을 하는 메서드

array([1, 2, 3, 4, 5, 6, 7, 8])