## Numpy Indexing & Slicing

Indexing

In [6]:
a_list = [[1, 2, 3], ['a','b', 'c']]
a_list[1][1]

'b'

In [7]:
import numpy as np 
a_arr = np.array([[1, 2, 3], [4, 5, 6]])
a_arr[1][1]

5

In [8]:
a_arr[1,1]

5

In [11]:
#리스트는 안됨
a_list[1,1]

TypeError: list indices must be integers or slices, not tuple

Slicing

In [18]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]], int)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
a[:2,:2]

array([[1, 2],
       [5, 6]])

In [21]:
a[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [22]:
a[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [46]:
a[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [45]:
a[1:,::2]

array([[ 5,  7],
       [ 9, 11]])