### Numpy Creation

arange

In [3]:
import numpy as np 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0, 5, 0.5)       ## 0에서부터 5까지 0.5 단위로 만들기

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [5]:
a = list(rang(0.5, 0.5))        ## 안됨. 실수는 range에서 사용할 수 없다

NameError: name 'rang' is not defined

In [6]:
np.arange(0, 5, 0.5).tolist()       ## 위에를 굳이 사용하고 싶다면 'tolist()'사용하면됨.

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

In [8]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
x = np.arange(-1, 1, 100)   # -1에서 1까지 100개를 만들어라
y = np.sin(x)

### ones, zeros and empty

In [14]:
np.zeros(shape=(10,), dtype=np.int8)    ## 원소가 10개인 벡터 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [15]:
np.ones((2, 5))     # 2 x 5 - 값이 1인 matrix 생성
                    # shape을 안써줘도 되고, int를 안써줘도 만들수 있는 것이 numpy 장점

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

empty

In [17]:
np.empty((3, 5))    ## 메모리가 초기화되어 있지 않음.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Something like

In [18]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [19]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [20]:
np.empty_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

### identity (단위 행렬)

In [22]:
np.identity(n=3, dtype=np.int32)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### eye (대각선 1인 행렬)

In [24]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.eye(3, 5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

### diag(대각 행렬의 값을 추출)

In [34]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [35]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
np.diag(matrix, k=1)

array([1, 5])

## Random sampleing

In [39]:
np.random.seed(2021)

In [40]:
np.random.uniform(0, 1, 10).reshape(2,5)    # 균등 분포(최소, 최대, 개수)

array([[0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328],
       [0.12816238, 0.17899311, 0.75292543, 0.66216051, 0.78431013]])

In [41]:
np.random.normal(0, 1, 10).reshape(2,5)    # 정규 분포(평균, 표준편차, 개수)

array([[ 0.10641374,  0.42215483,  0.12420684, -0.83795346,  0.4090157 ],
       [ 0.10275122, -1.90772239,  1.1002243 , -1.40232506, -0.22508127]])