## Numpy operation

In [1]:
import numpy as np

## sum()

In [2]:
test_array = np.arange(1,11)
test_array.sum()

55

In [3]:
test_array.sum(dtype=np.float32)

55.0

## axis

In [4]:
matrix = np.arange(1,13).reshape(3,4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
matrix.sum()

78

In [6]:
matrix.sum(axis=0)

array([15, 18, 21, 24])

In [7]:
matrix.sum(axis=1)

array([10, 26, 42])

### mean & std (평균 및 표준편차)

In [8]:
matrix.mean()

6.5

In [9]:
matrix.mean(axis=0)

array([5., 6., 7., 8.])

In [10]:
matrix.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [11]:
# Standard deviation
matrix.std()

3.452052529534663

In [12]:
matrix.std().round(4)   # 반올림해서 소숫점 이하 4자리까지 

3.4521

### Mathematical functions

In [13]:
np.exp(matrix)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

### Concatenate (Array를 합치는 함수)

### mathematical funtions

In [14]:
np.exp(matrix)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [15]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [16]:
b = np.array([[5, 6]])
b

array([[5, 6]])

In [17]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
c = np.arange(6).reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
np.hstack((a,c))        ## a, c를 옆으로 묶어보는 경우

array([[1, 2, 0, 1, 2],
       [3, 4, 3, 4, 5]])

In [21]:
np.concatenate((a,c), axis=1)

array([[1, 2, 0, 1, 2],
       [3, 4, 3, 4, 5]])

In [22]:
np.hstack((a,b))    # (2,2), (1,2)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [23]:
np.hstack((a, b.T))     # (2, 2),  (2, 1)

array([[1, 2, 5],
       [3, 4, 6]])

### Operations between arrays

In [25]:
a + a

array([[2, 4],
       [6, 8]])

In [27]:
a - a

array([[0, 0],
       [0, 0]])

In [26]:
a * a

array([[ 1,  4],
       [ 9, 16]])

### dot product

In [28]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [29]:
b = np.arange(6).reshape(2,3)       # b = a.T
b

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
a.dot(b)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [31]:
b.dot(a)

array([[10, 13],
       [28, 40]])

In [32]:
np.dot(a,b)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

### Broadcasting (Shape이 다른 배열간 연산)

In [34]:
scalar = 3
a + scalar

array([[3, 4],
       [5, 6],
       [7, 8]])

In [35]:
a * scalar

array([[ 0,  3],
       [ 6,  9],
       [12, 15]])

In [36]:
d = np.arange(10,21,10)
d

array([10, 20])

In [37]:
a + d

array([[10, 21],
       [12, 23],
       [14, 25]])