### Numpy Comparison

In [1]:
import numpy as np

### All & Any

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [4]:
np.any(a > 5), np.all(a > 5)

(True, False)

In [6]:
np.any(a > 10), np.all(a < 10)

(False, True)

### Logicl operation

In [9]:
a = np.array([1, 3, 0], float)
b = np.logical_and(a>0, a<3)    # 0 < a < 3
b

array([ True, False, False])

In [10]:
c = np.logical_or(a>0, a<3)     # a < 0 or a  > 3
c

array([ True,  True,  True])

In [11]:
np.where(a > 0)

(array([0, 1], dtype=int64),)

In [12]:
# Nan --> Not a Number, np-NaN
# Inf --> infinite(무한대값), np-Inf
x = np.array([1, np.NaN, np.Inf])
x

array([ 1., nan, inf])

In [13]:
np.isnan(x)

array([False,  True, False])

In [15]:
np.isnan(x).sum()

1

In [17]:
X = np.arange(1000, dtype=np.float32)
X[500] = np.NaN

In [18]:
np.isnan(X).sum()

1

In [19]:
np.isfinite(x)

array([ True, False, False])

In [23]:
len(x) - np.isfinite(x).sum()

2

### argmax & argmin

In [25]:
a = np.array([1,2,4,5,8,78,23,2]).reshape(2,-1)
a

array([[ 1,  2,  4,  5],
       [ 8, 78, 23,  2]])

In [27]:
np.argmax(a), np.argmin(a)   ## 최대값 또는 최소값의 "인덱스"를 줘라.

(5, 0)

In [28]:
a = np.array([[1, 2, 4, 7], [9, 88, 6, 45], [8, 78, 23, 3]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 8, 78, 23,  3]])

In [29]:
np.argmax(a, axis=0)

array([1, 1, 2, 1], dtype=int64)

In [30]:
np.argmax(a, axis=1)

array([3, 1, 1], dtype=int64)