In [24]:
## 문제1
import numpy as np 
np.arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [99]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
## 문제2

In [43]:
## 문제3
test_array = np.array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
test_array

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [44]:
## 문제4
t_list = [[[0, 1, 2], [3, 4, 5], [6, 7, 8]]]
tensor = np.array(t_list)
tensor

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [ ]:
## 문제5


In [26]:
## 문제6
np.identity(n=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
## 문제7
a_array = np.array([1,3, 5, 7, 11, 13, 15, 20, 30]).reshape(3,-1)
a_array

array([[ 1,  3,  5],
       [ 7, 11, 13],
       [15, 20, 30]])

In [89]:
a_array.sum(axis=1)

array([ 9, 31, 65])

In [90]:
a_array.sum(axis=0)

array([23, 34, 48])

In [94]:
## 문제 8

#행 평균
a_array.mean(axis=1)

array([ 3.        , 10.33333333, 21.66666667])

In [95]:
#열 평균
a_array.mean(axis=0)

array([ 7.66666667, 11.33333333, 16.        ])

In [21]:
## 문제9

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])