In [15]:
import numpy as np 
np.random.seed(2001)

In [16]:
# 1. 10 부터 49까지의 값을 가지는 벡터를 만드시오.
vec = np.arange(10, 50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [17]:
# 2. 위(1번) 벡터의 순서를 바꾸시오.
inv_vec = vec[::-1]
inv_vec

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [18]:
# 3. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드시오.
np.eye(1, 10, k=4)

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [19]:
# 4. 0부터 8까지의 값을 가지는 3x3 행렬을 만드시오.
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
# 5. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드시오.
given_vec = np.array([1,2,0,0,4,0])
given_vec[given_vec != 0]

array([1, 2, 4])

In [21]:
# 6. 3x3 단위 행렬(identity matrix)을 만드시오.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# 7. 난수 원소를 가지는 3x3 행렬을 만들고 최대값/최소값 원소를 찾으시오.
rand_mat = np.random.uniform(0, 1, 9).reshape(3,3)
rand_mat


array([[0.16712564, 0.08099804, 0.96022574],
       [0.93845024, 0.62085885, 0.42560197],
       [0.68978129, 0.24203462, 0.36660064]])

In [23]:
np.max(rand_mat), np.min(rand_mat), np.argmax(rand_mat), np.argmin(rand_mat)


(0.9602257400218493, 0.0809980368884986, 2, 1)

In [24]:
# 8. 위(7번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하시오.
# 행 평균
np.mean(rand_mat, axis=1)

array([0.40278314, 0.66163702, 0.43280552])

In [25]:
# 열 평균
np.mean(rand_mat, axis=0)

array([0.59845239, 0.3146305 , 0.58414278])

In [26]:
# 9. 다음의 행렬을 만드시오.
# 1 matrix
one = np.eye(5, k=1)
one

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [27]:
# 2 matrix
two = 2 * np.eye(5)
two

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

In [28]:
three = 3 * np.eye(5, k=-1)
three


array([[0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.]])

In [29]:
one + two + three


array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [30]:
np.eye(5, k=1) + 2 * np.eye(5) + 3 * np.eye(5, k=-1)


array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])